---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
        - id: check-yaml
        - id: check-merge-conflict
        - id: debug-statements
        - id: end-of-file-fixer
        - id: mixed-line-ending
        - id: trailing-whitespace
        - id: check-added-large-files
    - repo: https://github.com/jumanjihouse/pre-commit-hooks
      rev: 3.0.0
      hooks:
        - id: shellcheck
    - repo: https://github.com/markdownlint/markdownlint/
      rev: v0.12.0
      hooks:
        - id: markdownlint
    # Python linters
    - repo: https://github.com/psf/black
      rev: 23.12.0
      hooks:
          - id: black
    - repo: https://github.com/pycqa/isort
      rev: 5.13.1
      hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
    - repo: https://github.com/pycqa/pydocstyle
      rev: 6.3.0
      hooks:
      -   id: pydocstyle
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.7.1
      hooks:
      -   id: mypy
    - repo: local
      hooks:
          # Note: pylint to be run locally:
          # https://pylint.pycqa.org/en/latest/user_guide/pre-commit-integration.html
          - id: pylint
            name: pylint
            entry: pylint
            language: system
            types: [python]
            args:
              [
                --rcfile=.pylintrc
              ]
      # C++ linters
    - repo: https://github.com/pocc/pre-commit-hooks
      rev: v1.3.5
      # Must include this directory in files as .git is in parent
      hooks:
        - id: clang-format
          args: [
              -i,  # Fix inplace
              -style=Google
          ]
        - id: clang-tidy
          args:
            - "-p=build/"
        - id: cppcheck
          args:
            - "--inline-suppr"  # Enable inline suppression
        - id: cpplint
          args: ["--filter=-legal/copyright,-build/include_order,-whitespace/comments"]
        - id: include-what-you-use
          args:
            - "-Xiwyu"  # Xiwyu comes before iwyu arguments
            - "--error"
            - "-Xiwyu"
            - "--mapping_file=.linters/iwyu.imp"
            - "-Xiwyu"
            - "--update_comments"
